/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SamveraCard {
        /**
          * Action button link
         */
        "actionLink": string;
        /**
          * Title
         */
        "cardTitle": string;
        /**
          * Description
         */
        "description": string;
        /**
          * Image url
         */
        "imgUrl": string;
    }
    interface SamveraTodoList {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSamveraCardElement extends Components.SamveraCard, HTMLStencilElement {
    }
    var HTMLSamveraCardElement: {
        prototype: HTMLSamveraCardElement;
        new (): HTMLSamveraCardElement;
    };
    interface HTMLSamveraTodoListElement extends Components.SamveraTodoList, HTMLStencilElement {
    }
    var HTMLSamveraTodoListElement: {
        prototype: HTMLSamveraTodoListElement;
        new (): HTMLSamveraTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "samvera-card": HTMLSamveraCardElement;
        "samvera-todo-list": HTMLSamveraTodoListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SamveraCard {
        /**
          * Action button link
         */
        "actionLink"?: string;
        /**
          * Title
         */
        "cardTitle"?: string;
        /**
          * Description
         */
        "description"?: string;
        /**
          * Image url
         */
        "imgUrl"?: string;
    }
    interface SamveraTodoList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "samvera-card": SamveraCard;
        "samvera-todo-list": SamveraTodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "samvera-card": LocalJSX.SamveraCard & JSXBase.HTMLAttributes<HTMLSamveraCardElement>;
            "samvera-todo-list": LocalJSX.SamveraTodoList & JSXBase.HTMLAttributes<HTMLSamveraTodoListElement>;
        }
    }
}
